// 예외처리
// try & catch / throw / expn 예외변수
// try 부분에 예외가 발생하면 바로 catch로 넘어간다.
/*
 try
 {
    if(num2 == 0)
    {
        throw num1;
    }
    cout<<"blahblah"<<endl;
 }
 catch(int expn)